version: "3.7"

services:
  back-web:
    build: ./docker/nginx_back
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      # 画像やファイルなど、php 以外は nginx が直接扱うので、nginx にもbackendをマウントする
      - ../backend/public:/work/backend/public
      - ../backend/storage:/work/backend/storage
    depends_on:
      - server
    ports:
      - 82:80
      - 443:443

  server:
    build:
      args:
        - DB_CONNECTION=${MYSQL_DB_CONNECTION}
        - DB_HOST=${MYSQL_DB_HOST}
        - DB_DATABASE=${MYSQL_DATABASE}
        - DB_USERNAME=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
        - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
        - APP_URL=${APP_URL}
        - MAIL_MAILER=${MAIL_MAILER}
        - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
    volumes:
      - ../backend:/work/backend
      - ./docker/php/bash/.bash_history:/root/.bash_history
      - ./docker/php/bash/psysh:/root/.config/psysh
    depends_on:
      - db

  db:
    build: ./docker/mysql
    volumes:
      - ./docker/mysql/db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - 8882:80
    volumes:
      - ./docker/pma/sessions:/sessions 
